export interface Wallpaper {
  id: string
  name: string
  /** Full-size image. */
  url: string
  /** Small preview, also used as a blurred placeholder while `url` loads. */
  thumb: string
  /** UI accent colour that suits the wallpaper. */
  accent: string
}

// Generated by `npm run wallpapers` (see scripts/wallpapers/).
export const wallpapers: Wallpaper[] = [
  { id: 'vestra', name: 'Vestra', url: '/wallpapers/vestra.jpg', thumb: '/wallpapers/vestra-thumb.jpg', accent: '#f0a36b' },
]

export const DEFAULT_WALLPAPER = 'vestra'

export const findWallpaper = (id: string) => wallpapers.find((w) => w.id === id) ?? wallpapers[0]
