import {
  Activity,
  Aperture,
  ArrowDownToLine,
  AudioLines,
  BellRing,
  Bird,
  Blocks,
  Bookmark,
  BookOpen,
  Bot,
  Cable,
  Cctv,
  ChartLine,
  CircuitBoard,
  Clapperboard,
  Code,
  Container,
  Cpu,
  Download,
  FileText,
  Fingerprint,
  FlaskConical,
  Gamepad2,
  Gauge,
  GitBranch,
  Globe,
  Hash,
  Headphones,
  Joystick,
  KeyRound,
  Layers,
  LayoutDashboard,
  Library,
  Lightbulb,
  ListTodo,
  MessageCircle,
  MessageSquareText,
  MessagesSquare,
  Music,
  NotebookPen,
  Palette,
  Pickaxe,
  PiggyBank,
  Radar,
  Radio,
  RadioTower,
  ReceiptText,
  RefreshCw,
  Route,
  Rss,
  ScrollText,
  Search,
  ShieldBan,
  ShieldCheck,
  StickyNote,
  Store,
  TrendingUp,
  Tv,
  Wallet,
  WandSparkles,
  Waypoints,
  Workflow,
  Zap,
} from 'lucide-react'
import type { AppInfo } from './types'

const GB = 1e9

/**
 * Every app Plumos knows about. The home screen shows the ones in the apps
 * store's `installed` list; the App Store shows all of them.
 */
export const catalog: AppInfo[] = [
  {
    id: 'android',
    name: 'Android 13',
    tagline: 'A full Android phone, running on your server',
    description:
      'Run Android apps from any browser. Great for apps that only exist on phones, for testing, or for giving an AI agent a phone of its own.',
    category: 'virtual-machines',
    developer: 'Plumos',
    version: '13.0',
    icon: { type: 'art', art: 'android' },
    kind: 'vm',
    vm: { os: 'android', cpus: 4, memoryGb: 4, diskGb: 32 },
    size: 3.2 * GB,
  },
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    tagline: 'Home automation that puts local control first',
    description:
      'Control your lights, sensors, locks and thermostats from one place, with automations that keep running even when the internet is down.',
    category: 'smart-home',
    developer: 'Home Assistant',
    version: '2026.9.1',
    icon: { type: 'art', art: 'home-assistant' },
    port: 8123,
    size: 1.1 * GB,
  },
  {
    id: 'hermes-agent',
    name: 'Hermes Agent',
    tagline: 'A personal AI agent that works for you',
    description:
      'An autonomous assistant that can browse, write, run tasks and use your other apps, powered by local or cloud models of your choice.',
    category: 'ai',
    developer: 'Nous Research',
    version: '0.9.2',
    icon: { type: 'art', art: 'hermes-agent' },
    port: 3200,
    size: 0.8 * GB,
  },
  {
    id: 'immich',
    name: 'Immich',
    tagline: 'Photo and video backup from your phone',
    description:
      'Automatically back up every photo and video from your phone, then browse by date, place and person — without handing your memories to anyone else.',
    category: 'files',
    developer: 'Immich',
    version: '1.140.0',
    icon: { type: 'art', art: 'immich' },
    port: 2283,
    size: 1.6 * GB,
  },
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    tagline: 'Stream your movies, shows and music',
    description:
      'A free media server for your own collection. Stream to your TV, phone or browser with beautiful posters and metadata.',
    category: 'media',
    developer: 'Jellyfin',
    version: '10.11.0',
    icon: { type: 'art', art: 'jellyfin' },
    port: 8096,
    size: 0.9 * GB,
  },
  {
    id: 'n8n',
    name: 'n8n',
    tagline: 'Workflow automation for technical people',
    description:
      'Connect your apps and services with a visual workflow editor, then add code wherever you need it. Hundreds of integrations built in.',
    category: 'automation',
    developer: 'n8n',
    version: '1.112.0',
    icon: { type: 'art', art: 'n8n' },
    port: 5678,
    size: 0.6 * GB,
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    tagline: 'Files, calendars and contacts in your own cloud',
    description:
      'Sync files across your devices, share folders with family, and keep your calendar and contacts on hardware you own.',
    category: 'files',
    developer: 'Nextcloud',
    version: '31.0.4',
    icon: { type: 'art', art: 'nextcloud' },
    port: 8085,
    size: 1.2 * GB,
  },
  {
    id: 'bitcoin-node',
    name: 'Bitcoin Node',
    tagline: 'Run your own full Bitcoin node',
    description:
      'Verify every transaction yourself, broadcast privately, and connect your wallets to a node you control.',
    category: 'bitcoin',
    developer: 'Bitcoin Core',
    version: '29.1',
    icon: { type: 'art', art: 'bitcoin-node' },
    port: 2100,
    size: 0.4 * GB,
  },
  {
    id: 'windows',
    name: 'Windows 11',
    tagline: 'A Windows PC in a browser tab',
    description:
      'Run Windows programs from any device on your network. Perfect for the one app that only runs on Windows.',
    category: 'virtual-machines',
    developer: 'Plumos',
    version: '24H2',
    icon: { type: 'art', art: 'windows' },
    kind: 'vm',
    vm: { os: 'windows', cpus: 4, memoryGb: 8, diskGb: 64 },
    size: 6.4 * GB,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    tagline: 'Run large language models locally',
    description:
      'Download and run open models on your own hardware, with an API that your other apps and agents can use.',
    category: 'ai',
    developer: 'Ollama',
    version: '0.12.3',
    icon: { type: 'art', art: 'ollama' },
    port: 11434,
    size: 2.3 * GB,
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    tagline: 'An open-source AI agent with a computer of its own',
    description:
      'An agent that can use a desktop, browser and terminal to get real work done, running entirely on your server.',
    category: 'ai',
    developer: 'OpenClaw',
    version: '2.4.0',
    icon: { type: 'art', art: 'openclaw' },
    port: 3300,
    size: 1.4 * GB,
  },
  {
    id: 'plex',
    name: 'Plex',
    tagline: 'Your personal media, on every screen',
    description:
      'Organise your movies, TV and music, and stream them to your devices at home or away.',
    category: 'media',
    developer: 'Plex',
    version: '1.42.1',
    icon: { type: 'art', art: 'plex' },
    port: 32400,
    path: '/web',
    size: 0.7 * GB,
  },

  // ---------- AI ----------
  {
    id: 'open-webui',
    name: 'Open WebUI',
    tagline: 'A polished chat app for your local models',
    description:
      'Chat with the models running in Ollama from a fast, familiar interface. Drop in a PDF to ask questions about it, compare two models side by side, and keep every conversation on your own server.',
    category: 'ai',
    developer: 'Open WebUI',
    version: '0.6.30',
    icon: { type: 'glyph', glyph: MessageSquareText, background: 'linear-gradient(150deg, #3f3f46 0%, #09090b 100%)' },
    port: 8080,
    size: 1.5 * GB,
    isNew: true,
    keywords: ['llm', 'chat', 'assistant'],
  },
  {
    id: 'comfyui',
    name: 'ComfyUI',
    tagline: 'Build image-generation pipelines visually',
    description:
      'Wire models, prompts and filters together as a graph of nodes, then generate images on your own graphics card. Save a workflow once and rerun it with a single click whenever inspiration strikes.',
    category: 'ai',
    developer: 'Comfy Org',
    version: '0.3.60',
    icon: { type: 'glyph', glyph: Palette, background: 'linear-gradient(150deg, #fde047 0%, #f97316 100%)' },
    port: 8188,
    size: 4.2 * GB,
    keywords: ['images', 'stable diffusion', 'art', 'nodes'],
  },
  {
    id: 'localai',
    name: 'LocalAI',
    tagline: 'A drop-in AI API that never leaves home',
    description:
      'Serve text, image and speech models behind the same API that many apps already speak. Point your tools at your server instead of the cloud and your prompts stay private.',
    category: 'ai',
    developer: 'LocalAI',
    version: '3.5.0',
    icon: { type: 'glyph', glyph: Cpu, background: 'linear-gradient(150deg, #2dd4bf 0%, #4f46e5 100%)' },
    port: 8093,
    size: 2.8 * GB,
    keywords: ['llm', 'api', 'models'],
  },
  {
    id: 'whisper',
    name: 'Whisper',
    tagline: 'Accurate speech-to-text on your own hardware',
    description:
      'Transcribe voice memos, meetings and podcasts in dozens of languages without uploading a single recording. Other apps, like Home Assistant, can use it to understand voice commands too.',
    category: 'ai',
    developer: 'Whisper ASR',
    version: '1.9.1',
    icon: { type: 'glyph', glyph: AudioLines, background: 'linear-gradient(150deg, #f9a8d4 0%, #f97316 100%)' },
    port: 9005,
    size: 1.9 * GB,
    keywords: ['transcription', 'speech', 'voice', 'subtitles'],
  },
  {
    id: 'librechat',
    name: 'LibreChat',
    tagline: 'One chat app for every AI model',
    description:
      'Switch between local models and cloud providers in a single, familiar chat window. Search your history, share presets with the family, and keep everyone’s conversations separate.',
    category: 'ai',
    developer: 'LibreChat',
    version: '0.8.0',
    icon: { type: 'glyph', glyph: Bot, background: 'linear-gradient(150deg, #8b5cf6 0%, #db2777 100%)' },
    port: 3080,
    size: 1.1 * GB,
    isNew: true,
    keywords: ['llm', 'chat', 'assistant'],
  },
  {
    id: 'invokeai',
    name: 'InvokeAI',
    tagline: 'A creative studio for AI image making',
    description:
      'Sketch, inpaint and upscale on an infinite canvas, with image models running on your own graphics card. Built for people who want real creative control, not just a prompt box.',
    category: 'ai',
    developer: 'Invoke',
    version: '6.7.0',
    icon: { type: 'glyph', glyph: WandSparkles, background: 'linear-gradient(150deg, #22d3ee 0%, #9333ea 100%)' },
    port: 9090,
    size: 5.6 * GB,
    isNew: true,
    keywords: ['images', 'art', 'canvas'],
  },

  // ---------- Media ----------
  {
    id: 'audiobookshelf',
    name: 'Audiobookshelf',
    tagline: 'Audiobooks and podcasts, right where you left off',
    description:
      'Stream your audiobooks and podcasts to any device, with your place synced between them. New episodes download on their own, so the car picks up exactly where the kitchen left off.',
    category: 'media',
    developer: 'Audiobookshelf',
    version: '2.29.0',
    icon: { type: 'glyph', glyph: Headphones, background: 'linear-gradient(150deg, #fbbf24 0%, #92400e 100%)' },
    port: 13378,
    size: 0.3 * GB,
    keywords: ['podcasts', 'audiobooks', 'listening'],
  },
  {
    id: 'navidrome',
    name: 'Navidrome',
    tagline: 'Your music collection, streamed anywhere',
    description:
      'A quick, lightweight music server that turns folders of albums into your own streaming service. It works with dozens of mobile players and happily handles libraries of half a million songs.',
    category: 'media',
    developer: 'Navidrome',
    version: '0.58.0',
    icon: { type: 'glyph', glyph: Music, background: 'linear-gradient(150deg, #67e8f9 0%, #0e7490 100%)' },
    port: 4533,
    size: 0.05 * GB,
    keywords: ['music', 'subsonic', 'albums', 'playlists'],
  },
  {
    id: 'kavita',
    name: 'Kavita',
    tagline: 'A reading room for comics, manga and books',
    description:
      'Organise comics, manga and e-books into a library that looks great on any screen. Read in the browser, keep your progress across devices, and share collections with the family.',
    category: 'media',
    developer: 'Kavita',
    version: '0.8.8',
    icon: { type: 'glyph', glyph: BookOpen, background: 'linear-gradient(150deg, #e879f9 0%, #86198f 100%)' },
    port: 5000,
    size: 0.2 * GB,
    keywords: ['comics', 'manga', 'ebooks', 'reading'],
  },
  {
    id: 'calibre-web',
    name: 'Calibre-Web',
    tagline: 'Browse, read and send your e-books',
    description:
      'A clean web front end for your Calibre library. Search by author or series, read in the browser, and send a book straight to your e-reader with one click.',
    category: 'media',
    developer: 'Calibre-Web',
    version: '0.6.25',
    icon: { type: 'glyph', glyph: Library, background: 'linear-gradient(150deg, #d6a36b 0%, #7c3f1d 100%)' },
    port: 8083,
    size: 0.25 * GB,
    keywords: ['ebooks', 'reading', 'library'],
  },
  {
    id: 'sonarr',
    name: 'Sonarr',
    tagline: 'Never miss an episode again',
    description:
      'Sonarr keeps an eye out for new episodes of the shows you follow, fetches them in the quality you like, and files them neatly for your media server. Your library stays complete without lifting a finger.',
    category: 'media',
    developer: 'Sonarr',
    version: '4.0.15',
    icon: { type: 'glyph', glyph: Tv, background: 'linear-gradient(150deg, #38bdf8 0%, #1e3a8a 100%)' },
    port: 8989,
    size: 0.2 * GB,
    keywords: ['tv', 'shows', 'series'],
  },
  {
    id: 'radarr',
    name: 'Radarr',
    tagline: 'Your movie wishlist, on autopilot',
    description:
      'Add the films you want to watch and Radarr finds, downloads and organises them for Jellyfin or Plex. When a better copy turns up later, it quietly upgrades it for you.',
    category: 'media',
    developer: 'Radarr',
    version: '5.27.5',
    icon: { type: 'glyph', glyph: Clapperboard, background: 'linear-gradient(150deg, #fcd34d 0%, #c2410c 100%)' },
    port: 7878,
    size: 0.2 * GB,
    keywords: ['movies', 'films'],
  },
  {
    id: 'prowlarr',
    name: 'Prowlarr',
    tagline: 'One place to manage every indexer',
    description:
      'Set up your sources once and Prowlarr keeps Sonarr, Radarr and friends in sync. Test, rank and troubleshoot them all from a single tidy page.',
    category: 'media',
    developer: 'Prowlarr',
    version: '2.0.5',
    icon: {
      type: 'glyph',
      glyph: Radar,
      background: 'linear-gradient(150deg, #3f3f46 0%, #18181b 100%)',
      color: '#fb923c',
    },
    port: 9696,
    size: 0.15 * GB,
    keywords: ['indexers', 'search'],
  },
  {
    id: 'transmission',
    name: 'Transmission',
    tagline: 'A simple, lightweight download client',
    description:
      'A no-fuss BitTorrent client with a clean web interface. Queue up downloads, slow things down in the evening, and let it quietly get on with the job.',
    category: 'media',
    developer: 'Transmission',
    version: '4.0.6',
    icon: { type: 'glyph', glyph: ArrowDownToLine, background: 'linear-gradient(150deg, #fca5a5 0%, #dc2626 100%)' },
    port: 9091,
    size: 0.03 * GB,
    keywords: ['torrent', 'downloads'],
  },
  {
    id: 'qbittorrent',
    name: 'qBittorrent',
    tagline: 'A full-featured download client in your browser',
    description:
      'Everything you expect from a desktop torrent client, available from any browser at home. Categories, RSS rules, scheduling and search plug-ins are all built in.',
    category: 'media',
    developer: 'qBittorrent',
    version: '5.1.2',
    icon: {
      type: 'glyph',
      glyph: Download,
      background: 'linear-gradient(150deg, #f8fafc 0%, #cbd5e1 100%)',
      color: '#2563eb',
    },
    port: 8091,
    size: 0.06 * GB,
    keywords: ['torrent', 'downloads'],
  },

  // ---------- Bitcoin ----------
  {
    id: 'mempool',
    name: 'Mempool',
    tagline: 'Explore the Bitcoin blockchain yourself',
    description:
      'Watch blocks being found and transactions waiting in line, all served by your own node. Check fees before you send and look up addresses without leaking them to a public website.',
    category: 'bitcoin',
    developer: 'Mempool',
    version: '3.2.1',
    icon: { type: 'glyph', glyph: Blocks, background: 'linear-gradient(150deg, #6366f1 0%, #1e1b4b 100%)' },
    port: 3006,
    size: 1.2 * GB,
    keywords: ['explorer', 'fees', 'blocks', 'transactions'],
  },
  {
    id: 'lightning-node',
    name: 'Lightning Node',
    tagline: 'Instant, low-fee Bitcoin payments',
    description:
      'Run a Lightning node powered by LND and send or receive bitcoin in seconds for a fraction of a cent. Open channels, balance your liquidity and connect your mobile wallet.',
    category: 'bitcoin',
    developer: 'Lightning Labs',
    version: '0.19.3',
    icon: {
      type: 'glyph',
      glyph: Zap,
      background: 'linear-gradient(150deg, #fde047 0%, #ca8a04 100%)',
      color: '#1c1917',
    },
    port: 2101,
    size: 0.3 * GB,
    keywords: ['lnd', 'lightning', 'payments', 'channels'],
  },
  {
    id: 'electrs',
    name: 'Electrs',
    tagline: 'Connect your wallets to your own node',
    description:
      'A speedy Electrum server that lets desktop and mobile wallets talk to your Bitcoin node instead of a stranger’s. Your balances and addresses stay between you and your server.',
    category: 'bitcoin',
    developer: 'Roman Zeyde',
    version: '0.10.10',
    icon: {
      type: 'glyph',
      glyph: Cable,
      background: 'linear-gradient(150deg, #475569 0%, #0f172a 100%)',
      color: '#fbbf24',
    },
    port: 2102,
    size: 0.1 * GB,
    keywords: ['electrum', 'wallet', 'server'],
  },
  {
    id: 'btcpay-server',
    name: 'BTCPay Server',
    tagline: 'Accept Bitcoin payments with no middleman',
    description:
      'Take payments in your online shop, at a market stall or for donations, straight into your own wallet. No processing fees, no sign-up, and nobody who can freeze your account.',
    category: 'bitcoin',
    developer: 'BTCPay Server Foundation',
    version: '2.2.1',
    icon: { type: 'glyph', glyph: Store, background: 'linear-gradient(150deg, #4ade80 0%, #14532d 100%)' },
    port: 23000,
    size: 0.9 * GB,
    keywords: ['payments', 'merchant', 'shop', 'invoices'],
  },
  {
    id: 'ride-the-lightning',
    name: 'Ride The Lightning',
    tagline: 'A friendly dashboard for your Lightning node',
    description:
      'Manage channels, review routing fees and send payments from a clean web dashboard. Works with the Lightning Node app straight out of the box.',
    category: 'bitcoin',
    developer: 'RTL',
    version: '0.15.6',
    icon: { type: 'glyph', glyph: LayoutDashboard, background: 'linear-gradient(150deg, #38bdf8 0%, #312e81 100%)' },
    port: 3008,
    size: 0.15 * GB,
    keywords: ['lightning', 'channels', 'dashboard'],
  },

  // ---------- Smart home ----------
  {
    id: 'frigate',
    name: 'Frigate NVR',
    tagline: 'Camera recording with on-device AI',
    description:
      'Frigate records your security cameras and uses local AI to spot people, cars and parcels. You get the alerts that matter, fewer false alarms, and footage that never leaves the house.',
    category: 'smart-home',
    developer: 'Frigate',
    version: '0.16.1',
    icon: { type: 'glyph', glyph: Cctv, background: 'linear-gradient(150deg, #64748b 0%, #1e293b 100%)' },
    port: 8971,
    size: 1.3 * GB,
    isNew: true,
    keywords: ['cameras', 'nvr', 'security', 'doorbell'],
  },
  {
    id: 'zigbee2mqtt',
    name: 'Zigbee2MQTT',
    tagline: 'Use Zigbee devices without the vendor hubs',
    description:
      'Pair lights, sensors and switches from dozens of brands with a single USB stick, then use them from Home Assistant or Node-RED. Say goodbye to a drawer full of proprietary bridges.',
    category: 'smart-home',
    developer: 'Zigbee2MQTT',
    version: '2.6.1',
    icon: { type: 'glyph', glyph: RadioTower, background: 'linear-gradient(150deg, #fbbf24 0%, #b45309 100%)' },
    port: 8099,
    size: 0.2 * GB,
    keywords: ['zigbee', 'sensors', 'lights'],
  },
  {
    id: 'esphome',
    name: 'ESPHome',
    tagline: 'Make your own smart sensors',
    description:
      'Turn tiny, inexpensive boards into sensors, switches and displays with a few lines of configuration. They appear in Home Assistant on their own, no cloud account required.',
    category: 'smart-home',
    developer: 'ESPHome',
    version: '2025.9.1',
    icon: {
      type: 'glyph',
      glyph: CircuitBoard,
      background: 'linear-gradient(150deg, #e2e8f0 0%, #94a3b8 100%)',
      color: '#0f172a',
    },
    port: 6052,
    size: 0.5 * GB,
    keywords: ['diy', 'sensors', 'microcontroller'],
  },
  {
    id: 'homebridge',
    name: 'Homebridge',
    tagline: 'Bring every gadget to your phone’s home controls',
    description:
      'Homebridge lets devices that were never meant to work with your phone’s smart-home controls show up there anyway. Thousands of community plug-ins cover everything from robot vacuums to garage doors.',
    category: 'smart-home',
    developer: 'Homebridge',
    version: '1.11.0',
    icon: { type: 'glyph', glyph: Lightbulb, background: 'linear-gradient(150deg, #a78bfa 0%, #7e22ce 100%)' },
    port: 8581,
    size: 0.2 * GB,
    keywords: ['bridge', 'plugins', 'devices'],
  },

  // ---------- Automation ----------
  {
    id: 'node-red',
    name: 'Node-RED',
    tagline: 'Wire up your home with visual flows',
    description:
      'Drag nodes onto a canvas and connect them to automate anything from porch lights to web hooks. Perfect for tinkering, with thousands of community nodes to borrow from.',
    category: 'automation',
    developer: 'OpenJS Foundation',
    version: '4.1.0',
    icon: { type: 'glyph', glyph: Workflow, background: 'linear-gradient(150deg, #ef4444 0%, #7f1d1d 100%)' },
    port: 1880,
    size: 0.3 * GB,
    keywords: ['flows', 'iot', 'mqtt'],
  },
  {
    id: 'changedetection',
    name: 'Changedetection.io',
    tagline: 'Know when a web page changes',
    description:
      'Watch any page for price drops, restocks or new announcements and get a message the moment it changes. Narrow it down to just the part of the page you care about.',
    category: 'automation',
    developer: 'changedetection.io',
    version: '0.50.12',
    icon: { type: 'glyph', glyph: BellRing, background: 'linear-gradient(150deg, #a5f3fc 0%, #0891b2 100%)' },
    port: 5003,
    size: 0.3 * GB,
    keywords: ['alerts', 'monitoring', 'prices', 'restock'],
  },
  {
    id: 'huginn',
    name: 'Huginn',
    tagline: 'Little agents that watch the web for you',
    description:
      'Build small agents that check websites, feeds and inboxes on a schedule, then act on what they find. Get a digest of new listings, a nudge when the weather turns, or a message when a parcel ships.',
    category: 'automation',
    developer: 'Huginn',
    version: '2025.9.4',
    icon: { type: 'glyph', glyph: Bird, background: 'linear-gradient(150deg, #94a3b8 0%, #334155 100%)' },
    port: 3007,
    size: 0.6 * GB,
    keywords: ['agents', 'scraping', 'digest', 'schedule'],
  },

  // ---------- Files & productivity ----------
  {
    id: 'syncthing',
    name: 'Syncthing',
    tagline: 'Keep folders in sync across your devices',
    description:
      'Continuous, device-to-device file sync between your server, laptops and phones. Nothing passes through someone else’s cloud, and older versions are kept so an accidental delete is never final.',
    category: 'files',
    developer: 'Syncthing Foundation',
    version: '2.0.9',
    icon: { type: 'glyph', glyph: RefreshCw, background: 'linear-gradient(150deg, #22d3ee 0%, #2563eb 100%)' },
    port: 8384,
    size: 0.04 * GB,
    keywords: ['sync', 'backup', 'folders'],
  },
  {
    id: 'paperless-ngx',
    name: 'Paperless-ngx',
    tagline: 'Scan it, search it, shred the paper',
    description:
      'Turn the pile of letters, receipts and manuals into a searchable archive. Drop in a scan and Paperless reads the text, tags it and files it away, so that warranty turns up in seconds.',
    category: 'files',
    developer: 'Paperless-ngx',
    version: '2.18.4',
    icon: { type: 'glyph', glyph: FileText, background: 'linear-gradient(150deg, #10b981 0%, #134e4a 100%)' },
    port: 8000,
    size: 0.9 * GB,
    keywords: ['documents', 'scan', 'ocr', 'receipts'],
  },
  {
    id: 'stirling-pdf',
    name: 'Stirling PDF',
    tagline: 'Every PDF tool you need, fully offline',
    description:
      'Merge, split, compress, sign and convert PDFs right in your browser, with nothing uploaded anywhere else. More than fifty tools, from text recognition to redaction, in one tidy toolbox.',
    category: 'files',
    developer: 'Stirling Tools',
    version: '1.4.0',
    icon: { type: 'glyph', glyph: Layers, background: 'linear-gradient(150deg, #fb923c 0%, #dc2626 100%)' },
    port: 8090,
    size: 0.6 * GB,
    isNew: true,
    keywords: ['pdf', 'merge', 'sign', 'convert'],
  },
  {
    id: 'joplin',
    name: 'Joplin Server',
    tagline: 'Notes and to-dos that sync everywhere',
    description:
      'The sync server for Joplin, the open-source note-taking app. Notebooks, checklists and web clippings stay in step between your desktop and phone, stored on your own drives.',
    category: 'files',
    developer: 'Joplin',
    version: '3.4.3',
    icon: { type: 'glyph', glyph: NotebookPen, background: 'linear-gradient(150deg, #3b82f6 0%, #1e1b4b 100%)' },
    port: 22300,
    size: 0.3 * GB,
    keywords: ['notes', 'notebooks', 'markdown'],
  },
  {
    id: 'linkwarden',
    name: 'Linkwarden',
    tagline: 'Bookmarks that never go missing',
    description:
      'Save links into collections and Linkwarden keeps a full copy of each page, with a screenshot and PDF too. When a site vanishes years later, your copy is still right there.',
    category: 'files',
    developer: 'Linkwarden',
    version: '2.12.1',
    icon: { type: 'glyph', glyph: Bookmark, background: 'linear-gradient(150deg, #c4b5fd 0%, #6d28d9 100%)' },
    port: 3005,
    size: 0.5 * GB,
    isNew: true,
    keywords: ['bookmarks', 'archive', 'read later'],
  },
  {
    id: 'photoprism',
    name: 'PhotoPrism',
    tagline: 'A smart, searchable library for your photos',
    description:
      'Browse decades of pictures by place, colour, face or subject, all tagged automatically on your own hardware. A world map shows exactly where each memory was made.',
    category: 'files',
    developer: 'PhotoPrism',
    version: '250921',
    icon: { type: 'glyph', glyph: Aperture, background: 'linear-gradient(150deg, #f472b6 0%, #7c3aed 100%)' },
    port: 2342,
    size: 1.8 * GB,
    keywords: ['photos', 'pictures', 'gallery', 'faces'],
  },
  {
    id: 'memos',
    name: 'Memos',
    tagline: 'A quiet place for quick thoughts',
    description:
      'Jot down ideas, links and snippets in a private timeline that feels like a journal crossed with a chat. Markdown, tags and fast search keep everything easy to find again.',
    category: 'files',
    developer: 'Memos',
    version: '0.25.1',
    icon: {
      type: 'glyph',
      glyph: StickyNote,
      background: 'linear-gradient(150deg, #fde68a 0%, #f59e0b 100%)',
      color: '#451a03',
    },
    port: 5230,
    size: 0.06 * GB,
    keywords: ['notes', 'journal', 'ideas'],
  },
  {
    id: 'vikunja',
    name: 'Vikunja',
    tagline: 'To-do lists for the whole household',
    description:
      'Plan chores, projects and shopping with lists, boards and timelines. Share a board with the family and tick things off together.',
    category: 'files',
    developer: 'Vikunja',
    version: '1.0.0',
    icon: { type: 'glyph', glyph: ListTodo, background: 'linear-gradient(150deg, #5eead4 0%, #0369a1 100%)' },
    port: 3456,
    size: 0.12 * GB,
    keywords: ['tasks', 'todo', 'kanban', 'projects'],
  },

  // ---------- Networking ----------
  {
    id: 'tailscale',
    name: 'Tailscale',
    tagline: 'Reach home from anywhere, no port forwarding',
    description:
      'Put your server, laptop and phone on one private network that follows you around. Open your apps from a café or a hotel as if you were on the couch, without touching your router.',
    category: 'networking',
    developer: 'Tailscale',
    version: '1.88.2',
    icon: { type: 'glyph', glyph: Waypoints, background: 'linear-gradient(150deg, #52525b 0%, #18181b 100%)' },
    port: 8240,
    size: 0.12 * GB,
    keywords: ['vpn', 'remote access', 'mesh'],
  },
  {
    id: 'wireguard',
    name: 'WireGuard',
    tagline: 'A fast, modern VPN you run yourself',
    description:
      'Create a secure tunnel back to your home network in a few clicks and hand out access with a QR code. Browse safely on public Wi-Fi and reach every device at home.',
    category: 'networking',
    developer: 'wg-easy',
    version: '15.1.0',
    icon: { type: 'glyph', glyph: Route, background: 'linear-gradient(150deg, #f87171 0%, #9f1239 100%)' },
    port: 51821,
    size: 0.05 * GB,
    keywords: ['vpn', 'tunnel', 'remote access'],
  },
  {
    id: 'nginx-proxy-manager',
    name: 'Nginx Proxy Manager',
    tagline: 'Friendly addresses and HTTPS for every app',
    description:
      'Give your apps names like photos.example.com instead of port numbers, with free certificates that renew themselves. Everything is managed from a clean web dashboard.',
    category: 'networking',
    developer: 'jc21',
    version: '2.12.6',
    icon: { type: 'glyph', glyph: Globe, background: 'linear-gradient(150deg, #34d399 0%, #0e7490 100%)' },
    port: 81,
    size: 0.35 * GB,
    keywords: ['reverse proxy', 'ssl', 'https', 'domains'],
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    tagline: 'Know the moment something goes down',
    description:
      'Keep an eye on websites, apps and devices with checks every few seconds. Get a nudge on your phone when something stops answering, and share a tidy status page with the family.',
    category: 'networking',
    developer: 'Louis Lam',
    version: '2.0.2',
    icon: { type: 'glyph', glyph: Activity, background: 'linear-gradient(150deg, #4ade80 0%, #15803d 100%)' },
    port: 3001,
    size: 0.3 * GB,
    keywords: ['monitoring', 'status', 'alerts', 'uptime'],
  },
  {
    id: 'speedtest-tracker',
    name: 'Speedtest Tracker',
    tagline: 'Keep your internet provider honest',
    description:
      'Runs a speed test on a schedule and charts your download, upload and latency over weeks and months. When the connection slows down, you’ll have the receipts.',
    category: 'networking',
    developer: 'Alex Justesen',
    version: '1.6.5',
    icon: { type: 'glyph', glyph: Gauge, background: 'linear-gradient(150deg, #fcd34d 0%, #0d9488 100%)' },
    port: 8765,
    size: 0.2 * GB,
    keywords: ['internet', 'bandwidth', 'isp', 'latency'],
  },

  // ---------- Developer tools ----------
  {
    id: 'gitea',
    name: 'Gitea',
    tagline: 'Lightweight Git hosting for your projects',
    description:
      'Host repositories, issues and pull requests on your own server with a workflow you already know. Built-in CI and package registries mean side projects never have to leave home.',
    category: 'developer',
    developer: 'Gitea',
    version: '1.24.6',
    icon: { type: 'glyph', glyph: GitBranch, background: 'linear-gradient(150deg, #bef264 0%, #4d7c0f 100%)' },
    port: 3000,
    size: 0.25 * GB,
    keywords: ['git', 'code', 'repositories'],
  },
  {
    id: 'code-server',
    name: 'Code Server',
    tagline: 'A full code editor in any browser',
    description:
      'Pick up your projects from any device, even a tablet, with a complete editor, terminal and extensions running on your server. Your laptop battery will thank you.',
    category: 'developer',
    developer: 'Coder',
    version: '4.104.2',
    icon: { type: 'glyph', glyph: Code, background: 'linear-gradient(150deg, #0ea5e9 0%, #1e3a8a 100%)' },
    port: 8443,
    size: 0.7 * GB,
    keywords: ['ide', 'editor', 'programming'],
  },
  {
    id: 'grafana',
    name: 'Grafana',
    tagline: 'Beautiful dashboards for everything you measure',
    description:
      'Chart server stats, energy use, the weather or anything else with a timestamp. Build dashboards by dragging panels around, and get an alert when a line wanders where it shouldn’t.',
    category: 'developer',
    developer: 'Grafana Labs',
    version: '12.2.0',
    icon: { type: 'glyph', glyph: ChartLine, background: 'linear-gradient(150deg, #fdba74 0%, #dc2626 100%)' },
    port: 3003,
    size: 0.5 * GB,
    keywords: ['charts', 'metrics', 'dashboards', 'monitoring'],
  },
  {
    id: 'portainer',
    name: 'Portainer',
    tagline: 'Manage containers with a click',
    description:
      'See every container on your server, read its logs, restart services and deploy new stacks from a friendly web interface. Great for the curious and the careful alike.',
    category: 'developer',
    developer: 'Portainer',
    version: '2.33.1',
    icon: { type: 'glyph', glyph: Container, background: 'linear-gradient(150deg, #7dd3fc 0%, #0284c7 100%)' },
    port: 9000,
    size: 0.3 * GB,
    keywords: ['docker', 'containers', 'stacks'],
  },
  {
    id: 'dozzle',
    name: 'Dozzle',
    tagline: 'Live logs from every container',
    description:
      'Follow the logs of every container in real time from your browser, with search, filters and split views. No database and no setup, just logs.',
    category: 'developer',
    developer: 'Dozzle',
    version: '8.14.3',
    icon: {
      type: 'glyph',
      glyph: ScrollText,
      background: 'linear-gradient(150deg, #334155 0%, #020617 100%)',
      color: '#5eead4',
    },
    port: 8092,
    size: 0.02 * GB,
    keywords: ['docker', 'logs', 'debugging'],
  },
  {
    id: 'jupyterlab',
    name: 'JupyterLab',
    tagline: 'Notebooks for data, code and ideas',
    description:
      'Explore data, run experiments and write up what you found in interactive notebooks. Python, charts and your server’s graphics card are one browser tab away.',
    category: 'developer',
    developer: 'Project Jupyter',
    version: '4.4.9',
    icon: { type: 'glyph', glyph: FlaskConical, background: 'linear-gradient(150deg, #fed7aa 0%, #f97316 100%)' },
    port: 8888,
    size: 1.6 * GB,
    keywords: ['python', 'notebooks', 'data science'],
  },

  // ---------- Privacy & security ----------
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    tagline: 'Every password, in a vault you own',
    description:
      'A lightweight server for your password manager that works with the Bitwarden apps and browser extensions. Share logins with family and keep two-factor codes in sync on every device.',
    category: 'security',
    developer: 'Daniel García',
    version: '1.34.3',
    icon: { type: 'glyph', glyph: KeyRound, background: 'linear-gradient(150deg, #60a5fa 0%, #1e40af 100%)' },
    port: 8089,
    size: 0.1 * GB,
    keywords: ['passwords', 'password manager', '2fa', 'bitwarden'],
  },
  {
    id: 'pi-hole',
    name: 'Pi-hole',
    tagline: 'Block ads on every device at home',
    description:
      'Pi-hole filters ads and trackers for your whole network, so phones, TVs and smart speakers benefit without installing a thing. The live query log shows just how chatty your gadgets really are.',
    category: 'security',
    developer: 'Pi-hole',
    version: '6.1.4',
    icon: { type: 'glyph', glyph: ShieldBan, background: 'linear-gradient(150deg, #fb7185 0%, #be123c 100%)' },
    port: 8081,
    path: '/admin',
    size: 0.15 * GB,
    keywords: ['ads', 'ad blocker', 'dns', 'trackers'],
  },
  {
    id: 'adguard-home',
    name: 'AdGuard Home',
    tagline: 'Private DNS with ad and tracker blocking',
    description:
      'Filter ads, trackers and harmful sites for the whole network, with parental controls and encrypted DNS built in. Per-device rules let you be strict with the kids’ tablet and relaxed with yours.',
    category: 'security',
    developer: 'AdGuard',
    version: '0.107.65',
    icon: { type: 'glyph', glyph: ShieldCheck, background: 'linear-gradient(150deg, #6ee7b7 0%, #047857 100%)' },
    port: 3053,
    size: 0.08 * GB,
    keywords: ['ads', 'ad blocker', 'dns', 'parental controls'],
  },
  {
    id: 'authentik',
    name: 'Authentik',
    tagline: 'One sign-in for all your apps',
    description:
      'Put single sign-on and two-factor login in front of your self-hosted apps. Everyone at home gets one account and one password, and you decide who can open what.',
    category: 'security',
    developer: 'Authentik Security',
    version: '2025.8.3',
    icon: { type: 'glyph', glyph: Fingerprint, background: 'linear-gradient(150deg, #fbbf24 0%, #e11d48 100%)' },
    port: 9011,
    size: 0.7 * GB,
    keywords: ['sso', 'login', '2fa', 'accounts'],
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    tagline: 'Search the web without being tracked',
    description:
      'A metasearch engine that gathers results from dozens of sources without building a profile of you. Set it as your browser’s default and search like it’s nobody’s business.',
    category: 'security',
    developer: 'SearXNG',
    version: '2026.9.20',
    icon: { type: 'glyph', glyph: Search, background: 'linear-gradient(150deg, #7dd3fc 0%, #4338ca 100%)' },
    port: 8180,
    size: 0.2 * GB,
    keywords: ['search engine', 'privacy'],
  },

  // ---------- Social ----------
  {
    id: 'mastodon',
    name: 'Mastodon',
    tagline: 'Your own corner of the social web',
    description:
      'Run a Mastodon server for yourself, your family or your club, and follow people across the whole fediverse. No ads, no algorithm, and your posts live on your own hardware.',
    category: 'social',
    developer: 'Mastodon',
    version: '4.4.4',
    icon: { type: 'glyph', glyph: MessageCircle, background: 'linear-gradient(150deg, #818cf8 0%, #4338ca 100%)' },
    port: 3100,
    size: 1.4 * GB,
    keywords: ['fediverse', 'microblog', 'posts'],
  },
  {
    id: 'matrix-synapse',
    name: 'Matrix Synapse',
    tagline: 'Encrypted chat on your own server',
    description:
      'Synapse is a home server for Matrix, an open network for secure messaging and calls. Chat with the family end-to-end encrypted, and still talk to friends on other servers.',
    category: 'social',
    developer: 'Element',
    version: '1.139.0',
    icon: { type: 'glyph', glyph: Hash, background: 'linear-gradient(150deg, #2dd4bf 0%, #115e59 100%)' },
    port: 8008,
    size: 0.6 * GB,
    keywords: ['chat', 'messaging', 'encrypted'],
  },
  {
    id: 'nostr-relay',
    name: 'Nostr Relay',
    tagline: 'A home for your notes on Nostr',
    description:
      'Back up your Nostr posts to a relay you control, and open it up to friends if you like. Your identity and your history stay yours, whichever app you use.',
    category: 'social',
    developer: 'nostr-rs-relay',
    version: '0.9.0',
    icon: { type: 'glyph', glyph: Radio, background: 'linear-gradient(150deg, #a855f7 0%, #3b0764 100%)' },
    port: 4848,
    size: 0.05 * GB,
    keywords: ['nostr', 'relay', 'decentralized'],
  },
  {
    id: 'lemmy',
    name: 'Lemmy',
    tagline: 'Link sharing and discussion, federated',
    description:
      'Start forum-style communities around your interests and join others across the fediverse. Threads, votes and moderation tools, without a company in the middle.',
    category: 'social',
    developer: 'Lemmy',
    version: '0.19.13',
    icon: {
      type: 'glyph',
      glyph: MessagesSquare,
      background: 'linear-gradient(150deg, #f4f4f5 0%, #a1a1aa 100%)',
      color: '#18181b',
    },
    port: 1234,
    size: 0.5 * GB,
    keywords: ['forum', 'communities', 'fediverse'],
  },
  {
    id: 'freshrss',
    name: 'FreshRSS',
    tagline: 'A calm reader for the sites you love',
    description:
      'Follow blogs, news sites and video channels in one quiet timeline, with no algorithm deciding what you see. Syncs with popular reader apps on your phone.',
    category: 'social',
    developer: 'FreshRSS',
    version: '1.27.1',
    icon: { type: 'glyph', glyph: Rss, background: 'linear-gradient(150deg, #fdba74 0%, #c2410c 100%)' },
    port: 8084,
    size: 0.05 * GB,
    keywords: ['rss', 'news', 'feeds', 'blogs'],
  },

  // ---------- Finance ----------
  {
    id: 'actual-budget',
    name: 'Actual Budget',
    tagline: 'Budgeting that keeps your numbers private',
    description:
      'A fast, local-first budgeting app built around giving every dollar a job. See where the month is heading at a glance, and keep your finances off everyone else’s servers.',
    category: 'finance',
    developer: 'Actual',
    version: '25.9.0',
    icon: { type: 'glyph', glyph: PiggyBank, background: 'linear-gradient(150deg, #a78bfa 0%, #4c1d95 100%)' },
    port: 5006,
    size: 0.2 * GB,
    keywords: ['budget', 'money', 'envelopes', 'spending'],
  },
  {
    id: 'firefly-iii',
    name: 'Firefly III',
    tagline: 'A personal finance manager for the detail-minded',
    description:
      'Track accounts, bills and budgets with proper double-entry bookkeeping under the hood. Import bank statements, write rules to sort your spending, and watch your net worth grow.',
    category: 'finance',
    developer: 'James Cole',
    version: '6.4.0',
    icon: { type: 'glyph', glyph: Wallet, background: 'linear-gradient(150deg, #f87171 0%, #ea580c 100%)' },
    port: 8082,
    size: 0.4 * GB,
    keywords: ['money', 'budget', 'expenses', 'bills'],
  },
  {
    id: 'ghostfolio',
    name: 'Ghostfolio',
    tagline: 'All your investments on one page',
    description:
      'Follow stocks, funds and crypto across every broker in a single dashboard. See performance, allocation and dividends without handing your portfolio to a data broker.',
    category: 'finance',
    developer: 'Ghostfolio',
    version: '2.201.0',
    icon: {
      type: 'glyph',
      glyph: TrendingUp,
      background: 'linear-gradient(150deg, #1f2937 0%, #030712 100%)',
      color: '#4ade80',
    },
    port: 3333,
    size: 0.5 * GB,
    isNew: true,
    keywords: ['stocks', 'portfolio', 'investing', 'wealth'],
  },
  {
    id: 'invoice-ninja',
    name: 'Invoice Ninja',
    tagline: 'Invoices and quotes for your side business',
    description:
      'Send polished invoices and quotes, track time and expenses, and see who still owes you. Clients get a tidy portal to pay online, and your books stay on your own server.',
    category: 'finance',
    developer: 'Invoice Ninja',
    version: '5.12.20',
    icon: { type: 'glyph', glyph: ReceiptText, background: 'linear-gradient(150deg, #38bdf8 0%, #0f766e 100%)' },
    port: 9500,
    size: 0.8 * GB,
    keywords: ['invoices', 'billing', 'freelance', 'quotes'],
  },

  // ---------- Gaming ----------
  {
    id: 'minecraft-server',
    name: 'Minecraft Server',
    tagline: 'An always-on world for friends and family',
    description:
      'Host a world that’s always online for the kids and their friends. Pick the game version, manage who can join and take automatic backups from a simple browser console.',
    category: 'gaming',
    developer: 'itzg',
    version: '2026.9.0',
    icon: { type: 'glyph', glyph: Pickaxe, background: 'linear-gradient(150deg, #84cc16 0%, #365314 100%)' },
    port: 8444,
    size: 1.1 * GB,
    keywords: ['game server', 'multiplayer', 'blocks'],
  },
  {
    id: 'romm',
    name: 'RomM',
    tagline: 'A beautiful home for your retro games',
    description:
      'Scan your game collection and RomM adds cover art, descriptions and release details automatically. Browse it like a museum, then play many classics right in the browser.',
    category: 'gaming',
    developer: 'RomM',
    version: '4.2.0',
    icon: { type: 'glyph', glyph: Gamepad2, background: 'linear-gradient(150deg, #c084fc 0%, #6b21a8 100%)' },
    port: 8095,
    size: 0.45 * GB,
    isNew: true,
    keywords: ['retro', 'roms', 'games', 'collection'],
  },
  {
    id: 'emulatorjs',
    name: 'EmulatorJS',
    tagline: 'Retro consoles, playable in a browser tab',
    description:
      'Load your own game backups and play them with a controller or keyboard on any device at home. Save states live on the server, so you can move from laptop to TV mid-level.',
    category: 'gaming',
    developer: 'EmulatorJS',
    version: '1.9.2',
    icon: { type: 'glyph', glyph: Joystick, background: 'linear-gradient(150deg, #f472b6 0%, #be123c 100%)' },
    port: 3002,
    size: 0.4 * GB,
    keywords: ['retro', 'emulator', 'arcade'],
  },

  // ---------- Virtual machines ----------
  {
    id: 'ubuntu-desktop',
    name: 'Ubuntu Desktop',
    tagline: 'A complete Linux desktop, one click away',
    description:
      'A full Ubuntu desktop with a web browser, office suite and software centre, running as a virtual machine on your server. Try Linux without touching your computer, or give an AI agent a desktop of its own.',
    category: 'virtual-machines',
    developer: 'Plumos',
    version: '24.04 LTS',
    icon: { type: 'art', art: 'linux' },
    kind: 'vm',
    vm: { os: 'linux', cpus: 4, memoryGb: 8, diskGb: 64 },
    size: 5.8 * GB,
    isNew: true,
    keywords: ['linux', 'vm', 'desktop'],
  },
  {
    id: 'debian',
    name: 'Debian',
    tagline: 'Rock-solid Linux for tinkering',
    description:
      'A lean, dependable Debian system with a desktop you can open in any browser tab. Ideal for experiments you would rather keep well away from your main server.',
    category: 'virtual-machines',
    developer: 'Plumos',
    version: '13',
    icon: { type: 'art', art: 'linux' },
    kind: 'vm',
    vm: { os: 'linux', cpus: 2, memoryGb: 4, diskGb: 32 },
    size: 2.1 * GB,
    keywords: ['linux', 'vm', 'server'],
  },
]

export const DEFAULT_INSTALLED = [
  'android',
  'home-assistant',
  'hermes-agent',
  'immich',
  'jellyfin',
  'n8n',
  'nextcloud',
  'bitcoin-node',
  'windows',
  'ollama',
  'openclaw',
  'plex',
]

export const findApp = (id: string) => catalog.find((a) => a.id === id)
